# testing using CircleCI orb
# see https://on.cypress.io/circleci-orb

# for non-orb configuration see old commit
# https://github.com/cypress-io/cypress-example-kitchensink/blob/aabb10cc1bb9dee88e1bf28e0af5e9661427ee7a/circle.yml

# to use CircleCI orbs need to use version >= 2.1
version: 2.1
orbs:
  # use Cypress orb from CircleCI registry
  cypress: cypress-io/cypress@1

workflows:
  test:
    jobs:
      - checkout
      - run: npm ci
      - cypress/run:
          name: '2 machines using Chrome'
          # use executor with Chrome installed
          executor: cypress/browsers-chrome69
          # use browser "chrome" for running tests
          browser: chrome
          record: true
          parallel: true
          parallelism: 2
          group: '2x-chrome'
          spec: cypress/integration/google
          post-steps:
            - store_test_results:
                path: test-results     